# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CryptoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CryptoApp
  pod "SwiftChart"

  target 'CryptoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CryptoAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
